---

- hosts: webservers
  user: root

  vars_files:
    - app_vars.yml
  
  handlers:
    - include: 'app_handlers.yml'

  tasks:
  - include: setup_server_tasks.yml
  - include: setup_app_tasks.yml

- hosts: webservers
  user: app

  vars_files:
    - app_vars.yml

  handlers:
    - include: 'app_handlers.yml'

  tasks:
  - include: deploy_app_tasks.yml
